//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prbd_1819_g01.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("prbd_1819_g01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #Action.
        /// </summary>
        public static string BasketView_Action {
            get {
                return ResourceManager.GetString("BasketView_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #Author.
        /// </summary>
        public static string BasketView_Author {
            get {
                return ResourceManager.GetString("BasketView_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This Basket is for:.
        /// </summary>
        public static string BasketView_BasketIsFor {
            get {
                return ResourceManager.GetString("BasketView_BasketIsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear.
        /// </summary>
        public static string BasketView_Clear {
            get {
                return ResourceManager.GetString("BasketView_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        public static string BasketView_Confirm {
            get {
                return ResourceManager.GetString("BasketView_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string BasketView_Delete {
            get {
                return ResourceManager.GetString("BasketView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title.
        /// </summary>
        public static string BasketView_Title {
            get {
                return ResourceManager.GetString("BasketView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string BookDetailView_Add {
            get {
                return ResourceManager.GetString("BookDetailView_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author:.
        /// </summary>
        public static string BookDetailView_Author {
            get {
                return ResourceManager.GetString("BookDetailView_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Book Copies.
        /// </summary>
        public static string BookDetailView_Book_Copies {
            get {
                return ResourceManager.GetString("BookDetailView_Book_Copies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string BookDetailView_Cancel {
            get {
                return ResourceManager.GetString("BookDetailView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Categories:.
        /// </summary>
        public static string BookDetailView_Categories {
            get {
                return ResourceManager.GetString("BookDetailView_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear.
        /// </summary>
        public static string BookDetailView_Clear {
            get {
                return ResourceManager.GetString("BookDetailView_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aquisition Date.
        /// </summary>
        public static string BookDetailView_ColAquisitionDate {
            get {
                return ResourceManager.GetString("BookDetailView_ColAquisitionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID.
        /// </summary>
        public static string BookDetailView_ColID {
            get {
                return ResourceManager.GetString("BookDetailView_ColID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rented by.
        /// </summary>
        public static string BookDetailView_ColRentedBy {
            get {
                return ResourceManager.GetString("BookDetailView_ColRentedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string BookDetailView_Date {
            get {
                return ResourceManager.GetString("BookDetailView_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string BookDetailView_Delete {
            get {
                return ResourceManager.GetString("BookDetailView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editor:.
        /// </summary>
        public static string BookDetailView_Editor {
            get {
                return ResourceManager.GetString("BookDetailView_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISBN:.
        /// </summary>
        public static string BookDetailView_ISBN {
            get {
                return ResourceManager.GetString("BookDetailView_ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load.
        /// </summary>
        public static string BookDetailView_Load {
            get {
                return ResourceManager.GetString("BookDetailView_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Picture:.
        /// </summary>
        public static string BookDetailView_Picture {
            get {
                return ResourceManager.GetString("BookDetailView_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qty.
        /// </summary>
        public static string BookDetailView_Qty {
            get {
                return ResourceManager.GetString("BookDetailView_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string BookDetailView_Save {
            get {
                return ResourceManager.GetString("BookDetailView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title:.
        /// </summary>
        public static string BookDetailView_Title {
            get {
                return ResourceManager.GetString("BookDetailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add to Basket.
        /// </summary>
        public static string BooksView_AddToBasket {
            get {
                return ResourceManager.GetString("BooksView_AddToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Category Filter:.
        /// </summary>
        public static string BooksView_CategoryFilter {
            get {
                return ResourceManager.GetString("BooksView_CategoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear.
        /// </summary>
        public static string BooksView_Clear {
            get {
                return ResourceManager.GetString("BooksView_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Book.
        /// </summary>
        public static string BooksView_NewBook {
            get {
                return ResourceManager.GetString("BooksView_NewBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text Filter:.
        /// </summary>
        public static string BooksView_TextFilter {
            get {
                return ResourceManager.GetString("BooksView_TextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string CategoriesView_Add {
            get {
                return ResourceManager.GetString("CategoriesView_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #Books.
        /// </summary>
        public static string CategoriesView_Books {
            get {
                return ResourceManager.GetString("CategoriesView_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string CategoriesView_Cancel {
            get {
                return ResourceManager.GetString("CategoriesView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string CategoriesView_Delete {
            get {
                return ResourceManager.GetString("CategoriesView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string CategoriesView_Name {
            get {
                return ResourceManager.GetString("CategoriesView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        public static string CategoriesView_Update {
            get {
                return ResourceManager.GetString("CategoriesView_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à does not exist.
        /// </summary>
        public static string Error_DoesNotExist {
            get {
                return ResourceManager.GetString("Error_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à length must be &gt;= 3.
        /// </summary>
        public static string Error_LengthGreaterEqual3 {
            get {
                return ResourceManager.GetString("Error_LengthGreaterEqual3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à must match confirm password.
        /// </summary>
        public static string Error_MustMatchConfirmPassword {
            get {
                return ResourceManager.GetString("Error_MustMatchConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à must match password.
        /// </summary>
        public static string Error_MustMatchPassword {
            get {
                return ResourceManager.GetString("Error_MustMatchPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à not available.
        /// </summary>
        public static string Error_NotAvailable {
            get {
                return ResourceManager.GetString("Error_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à only numbers are accepted.
        /// </summary>
        public static string Error_NumberOnly {
            get {
                return ResourceManager.GetString("Error_NumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à required.
        /// </summary>
        public static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à to long !.
        /// </summary>
        public static string Error_ToLong {
            get {
                return ResourceManager.GetString("Error_ToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wrong password.
        /// </summary>
        public static string Error_WrongPassword {
            get {
                return ResourceManager.GetString("Error_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string LoginView_Cancel {
            get {
                return ResourceManager.GetString("LoginView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string LoginView_Login {
            get {
                return ResourceManager.GetString("LoginView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If your don&apos;t have a login and a password, click.
        /// </summary>
        public static string LoginView_Message_1 {
            get {
                return ResourceManager.GetString("LoginView_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à here.
        /// </summary>
        public static string LoginView_Message_2 {
            get {
                return ResourceManager.GetString("LoginView_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à to sign-up..
        /// </summary>
        public static string LoginView_Message_3 {
            get {
                return ResourceManager.GetString("LoginView_Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password:.
        /// </summary>
        public static string LoginView_Password {
            get {
                return ResourceManager.GetString("LoginView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pseudo:.
        /// </summary>
        public static string LoginView_Pseudo {
            get {
                return ResourceManager.GetString("LoginView_Pseudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string LoginView_Title {
            get {
                return ResourceManager.GetString("LoginView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Basket.
        /// </summary>
        public static string MainView_Basket {
            get {
                return ResourceManager.GetString("MainView_Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Books.
        /// </summary>
        public static string MainView_Books {
            get {
                return ResourceManager.GetString("MainView_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Categories.
        /// </summary>
        public static string MainView_Categories {
            get {
                return ResourceManager.GetString("MainView_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File.
        /// </summary>
        public static string MainView_File {
            get {
                return ResourceManager.GetString("MainView_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logout.
        /// </summary>
        public static string MainView_Logout {
            get {
                return ResourceManager.GetString("MainView_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rentals.
        /// </summary>
        public static string MainView_Rentals {
            get {
                return ResourceManager.GetString("MainView_Rentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users.
        /// </summary>
        public static string MainView_Users {
            get {
                return ResourceManager.GetString("MainView_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        public static string RentalView_RentalActions {
            get {
                return ResourceManager.GetString("RentalView_RentalActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Book.
        /// </summary>
        public static string RentalView_RentalBook {
            get {
                return ResourceManager.GetString("RentalView_RentalBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rental Date.
        /// </summary>
        public static string RentalView_RentalDate {
            get {
                return ResourceManager.GetString("RentalView_RentalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #Items.
        /// </summary>
        public static string RentalView_RentalItems {
            get {
                return ResourceManager.GetString("RentalView_RentalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #Open.
        /// </summary>
        public static string RentalView_RentalOpen {
            get {
                return ResourceManager.GetString("RentalView_RentalOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User.
        /// </summary>
        public static string RentalView_RentalUser {
            get {
                return ResourceManager.GetString("RentalView_RentalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Return Date.
        /// </summary>
        public static string RentalView_ReturnDate {
            get {
                return ResourceManager.GetString("RentalView_ReturnDate", resourceCulture);
            }
        }
    }
}
